# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-08 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=512)),
                ('address_line2', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('district', models.CharField(max_length=512)),
                ('taluka', models.CharField(max_length=512)),
                ('village', models.CharField(max_length=512, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=b'3e6be6ff-9e10-485f-9867-9d7f3d4f224b', max_length=128)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('logout', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('request_id', models.CharField(max_length=512, null=True)),
                ('uuId', models.CharField(default=b'7712b1cc-a47b-45c9-a7dc-8c8c98a9d772', max_length=512)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 16, 57, 34, 193627))),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('email', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
        migrations.AddField(
            model_name='login',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.OTP'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
    ]
