# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-17 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=1024, null=True)),
                ('point', models.FloatField()),
                ('price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('health_benefits', models.TextField(null=True)),
                ('nutrition_benefits', models.TextField(null=True)),
                ('unit', models.CharField(choices=[('GM', 'GM'), ('KG', 'KG'), ('ML', 'ML'), ('LTR', 'LTR')], max_length=64, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('show', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Quantities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('unit', models.CharField(choices=[('GM', 'GM'), ('KG', 'KG'), ('ML', 'ML'), ('LTR', 'LTR')], max_length=64)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=128)),
                ('update_type', models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('TRIVIAL', 'TRIVIAL')], default='TRIVIAL', max_length=128)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=128, null=True)),
                ('product', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VersionFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=1024, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Version')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'9ff5b2c4-aa6c-4e9e-9a6d-6d6519359b3c', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 17, 49, 42, 178402)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'24b8c5f5-fa3b-44f8-a29b-be144377dc3b', max_length=512),
        ),
        migrations.AddField(
            model_name='slider',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantities',
            field=models.ManyToManyField(to='veggies_models.Quantities'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
    ]
