# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0002_auto_20200917_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('image_type', models.CharField(choices=[('SLIDER', 'SLIDER'), ('BANNER', 'BANNER')], default='SLIDER', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('delivery_charges', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='created_by',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('WEEK', 'WEEK'), ('MONTH', 'MONTH'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Address'),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'682c5a15-0a6a-42bb-a4e4-39a16b3150c6', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 19, 21, 36, 712070)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'61844a04-5416-4545-ac5f-0e7c7d520162', max_length=512),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
    ]
