# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0003_auto_20200918_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincode',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'e0366c6b-ac29-42e7-bcab-fdb7cda43982', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 20, 21, 47, 896052)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'69225028-871e-4596-bbc7-3462d6999c6a', max_length=512),
        ),
    ]
