# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0004_auto_20200918_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saver_type', models.CharField(choices=[('WEEK', 'WEEK'), ('MONTH', 'MONTH')], default='WEEK', max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'ca72968a-835e-45c7-ae75-4cfb8fad5b7d', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 20, 48, 25, 190609)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'0be09066-5d28-44cc-a64a-9cb49dcbf999', max_length=512),
        ),
        migrations.AddField(
            model_name='saver',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Product'),
        ),
    ]
