# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-18 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0005_auto_20200918_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'0c033ca9-123a-4c57-ba72-f2ce13f6a6fd', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 20, 48, 28, 685457)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'eedd9f02-7afe-4d18-ba36-c620ebf16754', max_length=512),
        ),
    ]
