# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-19 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0006_auto_20200918_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=1024, null=True)),
                ('points', models.IntegerField()),
                ('price', models.FloatField()),
                ('deliveries', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('is_one_time_delivery', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User')),
                ('products', models.ManyToManyField(to='veggies_models.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'fcc68c99-259d-437f-a33e-8ac504c6bd25', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 10, 15, 25, 241583)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'6acde741-1523-4707-b642-882f18a79562', max_length=512),
        ),
        migrations.AlterField(
            model_name='saver',
            name='saver_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('MONTH', 'MONTH')], default='WEEK', max_length=100),
        ),
    ]
