# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-19 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0007_auto_20200919_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='does_hold_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'58a9b550-aa19-4b35-88be-433c67924ba4', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 11, 1, 31, 635300)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'f87c34a2-5f30-46c1-b445-860990ad1795', max_length=512),
        ),
    ]
