# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0008_auto_20200919_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plan_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plan_details', to='veggies_models.Quantities'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'5ba61c05-b80c-4a18-a41c-1c3f48ecedd4', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 14, 53, 42, 656256)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'97aef09e-df43-46a2-881e-4b536bffff4c', max_length=512),
        ),
    ]
