# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0009_auto_20200920_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='point',
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'bfe042c2-f597-49c0-b0e4-768d6a785117', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 17, 21, 54, 136763)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'4782db92-9263-4f59-a38f-f1240306c6d4', max_length=512),
        ),
    ]
