# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0010_auto_20200920_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('amount', models.FloatField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Quantities')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'a50c51a6-d6b7-4589-9921-2c826cf7d68c', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 3, 17, 14, 37045)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'0f4044fb-7cf2-496b-9ba9-e3678d7d49f5', max_length=512),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='veggies_models.OrderItem'),
        ),
    ]
