# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0011_auto_20200924_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Pincode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'abeaea3f-a78f-4e27-8c08-66c4993e6139', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 5, 29, 46, 719729)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'001e9dd4-92e9-4f37-8eba-a314fcb10975', max_length=512),
        ),
    ]
