# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-27 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0012_auto_20200924_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL'), ('HOLD', 'HOLD')], default='CREATED', max_length=64),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'b9a2a822-31b5-4f86-a443-c645e083f0a3', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 6, 53, 23, 952322)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'd9d936a5-bdeb-48d1-9e60-11db949913b3', max_length=512),
        ),
    ]
