# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-27 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0014_auto_20200927_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'99b23425-d1ad-4d31-9d39-a38dc923cbb6', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 9, 59, 0, 567099)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'380f4eb1-46dc-4f03-a9db-9e219711a544', max_length=512),
        ),
    ]
