# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-27 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0015_auto_20200927_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_response',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'546df99c-131e-4f8c-b7ff-1203bcdb131f', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 10, 2, 47, 749109)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'b8200abc-a55e-4674-a830-b37e1e1d9a89', max_length=512),
        ),
    ]
