# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0016_auto_20200927_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('is_customized', models.BooleanField(default=False)),
                ('delivery_no', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('EDITABLE', 'EDITABLE'), ('FREEZE', 'FREEZE'), ('DELIVERED', 'DELIVERED'), ('NOT_DELIVERED', 'NOT_DELIVERED')], default='SCHEDULED', max_length=128)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Basket')),
                ('extra_products', models.ManyToManyField(related_name='extra_products', to='veggies_models.Product')),
                ('products', models.ManyToManyField(to='veggies_models.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(20, 0))),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Basket'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'1c387994-7ac2-4f06-9205-294d6312383a', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 15, 37, 55, 823908)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'96b22b1b-da38-461c-899b-04f395137863', max_length=512),
        ),
        migrations.AddField(
            model_name='delivery',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Slot'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
        migrations.AddField(
            model_name='pincode',
            name='slot',
            field=models.ManyToManyField(to='veggies_models.Slot'),
        ),
    ]
