# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0017_auto_20200929_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveries',
            field=models.ManyToManyField(null=True, to='veggies_models.Delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'1c55bcb4-4d79-46ec-a8c5-fe448cf15e60', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='NORMAL', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 18, 42, 45, 695336)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'284cc578-7f7d-4a92-b6b2-1eeba63aad9a', max_length=512),
        ),
    ]
