# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0018_auto_20200929_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='extra_products',
            field=models.ManyToManyField(related_name='extra_products', to='veggies_models.OrderItem'),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'697363ca-7577-4b90-aed9-a68e5beed99f', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 19, 26, 28, 585650)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'968d59fa-f011-48de-9111-88546a035669', max_length=512),
        ),
    ]
