# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-30 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0019_auto_20200929_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Order')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='veggies_models.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'3f3b1cca-c842-4c7e-93ab-b7f59fe14ea9', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 4, 1, 5, 727085)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'5aebf977-4f4c-4156-9700-605250af44fc', max_length=512),
        ),
    ]
