# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-30 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0020_auto_20200930_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customization_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='max_points',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'7895ad91-7d62-4634-8006-9f2a958623a7', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 17, 46, 2, 844278)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'87a5e288-c650-4dc6-9c05-1392315c2f6a', max_length=512),
        ),
    ]
