# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-01 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0021_auto_20200930_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'66acf487-882b-4d45-9e0a-2eb68e4ba074', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 6, 57, 38, 304940)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'9c4bb714-1496-4d7c-aa68-c60a9c73ee6c', max_length=512),
        ),
    ]
