# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-01 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0022_auto_20201001_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customization_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_customized',
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'91a45b35-571f-48a8-b047-e7aeaf041850', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 7, 31, 2, 189207)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'b897b0f5-ee39-484a-af4a-dad75c25ba6a', max_length=512),
        ),
    ]
