# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-05 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0027_auto_20201005_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'a387e3d4-3ea6-4767-b6d9-12167fe4b695', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 0, 1, 58, 496890)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'0e252f8c-0695-4b7d-9bcb-e8c7dfc5f4c0', max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_details', to='veggies_models.Quantities'),
        ),
    ]
