# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-06 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0028_auto_20201005_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User')),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'0ed5c6f0-81f8-4459-9da0-58ec4d4259d9', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 11, 25, 4, 797754)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'f6b9000e-5915-48a4-9897-d07be854c0f3', max_length=512),
        ),
    ]
