# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0029_auto_20201006_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'272560c9-cddf-45f7-9e98-c0774fefd6b1', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 15, 15, 16, 58003)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'dde6e34f-5231-4f29-8c15-a73ea09cd54a', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('user', 'product')]),
        ),
    ]
