# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0030_auto_20201008_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'fdc512b1-0eac-4e07-92d3-0d6449a3568d', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 22, 7, 2, 113632)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'bf0b5270-adce-4f3e-8a99-70d4379e13c2', max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.FloatField(null=True),
        ),
    ]
