# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0031_auto_20201008_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'849a2255-4e88-40bc-be26-19ba58fe02c5', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 23, 8, 58, 155971)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'9f80abd5-0e0b-42bd-b4c2-933de7c98be3', max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='saver',
            unique_together=set([('saver_type', 'product')]),
        ),
    ]
