# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0032_auto_20201008_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address_for_delivery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address_here', to='veggies_models.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'8814d8e9-d347-4048-8c86-ab0fa278206d', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 23, 26, 4, 862544)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'252afc1a-a93f-48ea-8bf5-89fdfa2bbfb6', max_length=512),
        ),
    ]
