# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-09 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0033_auto_20201008_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('event', models.CharField(max_length=1024)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'6a7347f4-4ac5-4598-aa13-0099e814bd9b', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 23, 46, 31, 305010)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'557010cb-8f8e-4eae-880e-472de2016a5e', max_length=512),
        ),
    ]
