# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-10 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0034_auto_20201009_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'1b2fd319-b974-48a3-9931-e8d0d7fe8ba1', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 9, 35, 23, 202055)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'c0a44c49-aca2-47f1-b8f8-e8b4f20e3d2d', max_length=512),
        ),
    ]
