# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-12 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0036_auto_20201010_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_default_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_id',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'8e0207c6-243f-44ac-810a-832b04f8c432', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 22, 5, 45, 386811)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'dd8e816c-818c-4454-8eb4-bacd8df30526', max_length=512),
        ),
    ]
