# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0038_auto_20201021_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_sent_count',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'4eaab274-725d-4a2f-b031-5dfb104258c7', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 19, 52, 45, 11797)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'791b68c7-a9ca-4059-9305-d53ce5dc4479', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'6d43fce9-682f-4b1e-9138-605f0ba3e355', max_length=1024),
        ),
    ]
