# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0039_auto_20201021_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pincode',
            name='delivery_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'97290666-fb5d-43c0-a4c3-7e32e82177c1', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 21, 46, 15, 131347)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'd9e7aeec-8416-4340-a4f7-0a2e561a89ee', max_length=512),
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(null=True, to='veggies_models.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'70d50846-643f-4b25-9a62-adbc0810bfac', max_length=1024),
        ),
    ]
