# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0041_auto_20201024_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apply_count', models.IntegerField()),
                ('remaining_count', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('DELIVERED', 'DELIVERED'), ('NOT_DELIVERED', 'NOT_DELIVERED')], default='CONFIRMED', max_length=512),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'f5030196-dfca-4e7b-ac75-e6463b13529f', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 22, 11, 14, 494780)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'45e46288-1682-4ead-a392-b29592d7e5f1', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'45ebe45b-e492-4ef3-821c-4f9e0612b20b', max_length=1024),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Coupon'),
        ),
    ]
