# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0042_auto_20201029_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'a2b9ebef-e432-483f-a102-22db51c3f59b', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 0, 39, 41, 445244)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'5d3a63f2-3dcb-40ac-b44b-a4ad61d8544a', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'45bcda23-d998-4638-8f8b-a691a300c5c8', max_length=1024),
        ),
    ]
