# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 02:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0043_auto_20201030_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'66b7556c-b758-4cd8-bf7e-b9ee37faf3f1', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 8, 22, 9, 171167)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'1ec92bf5-e6a9-4235-9a93-a02398bde66c', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'f9dc4c1d-2b31-4617-928b-52b8fdb13c43', max_length=1024),
        ),
    ]
