# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0044_auto_20201030_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponAvail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='PricePerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'1a493fe2-e3b1-4d8d-b4bb-3e7ce14e016f', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 12, 32, 15, 850286)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'7ad41e15-d515-4160-9271-300520063815', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'492f46ad-2726-4c5f-ab05-7203df3a2fba', max_length=1024),
        ),
        migrations.AddField(
            model_name='priceperpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
        migrations.AddField(
            model_name='couponavail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggies_models.User'),
        ),
    ]
