# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0045_auto_20201030_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggies_models.Slot'),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'4cb8fea1-036b-4d0f-9e1c-9fd0d72b2d8b', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 7, 38, 5, 139782)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'f5fc39cf-73d4-4e54-9b0e-3aa060be4077', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'6f64cf53-8b11-480d-acc4-3bfaa39eaf2e', max_length=1024),
        ),
    ]
