# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-31 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0046_auto_20201031_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'e978b11a-0f09-43b9-acba-c94eedf57287', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 15, 44, 1, 696162)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'2f3cc632-778d-44d6-bac3-b6d3c2dffb09', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'a0607ae3-44ba-4060-b7fd-175c044948b2', max_length=1024),
        ),
    ]
