# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0047_auto_20201031_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extended_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_delivery', to='veggies_models.Delivery'),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'84c0b1c8-39f3-4cd2-bb2a-d05e864aa3ac', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 22, 11, 31, 377084)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'6516159d-0602-42e1-b505-f79730378c3f', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'd531630f-b4cf-4a57-97b5-fbb85519b27d', max_length=1024),
        ),
    ]
