# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0048_auto_20201102_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'30eb89bb-7482-43be-bf9a-46498ba16d61', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 22, 34, 41, 311674)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'b8b224d0-74e3-4d1c-a36b-f28f47750562', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'16357297-f149-439d-84fe-8b82e4e3e939', max_length=1024),
        ),
    ]
