# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0049_auto_20201102_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='with_basket_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'a8e647b4-46ea-4426-a7a5-965a189d78bc', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 0, 21, 43, 857429)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'a15dbe98-bfe2-4126-968c-04df97787910', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'c0bf57b8-d199-44b6-9ef1-985e84d8147b', max_length=1024),
        ),
    ]
