# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0051_auto_20201105_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliveries_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'824c33c3-3fd1-4b21-aefe-e338ebe7de47', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 42, 56, 840754)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'7accf29d-5827-47e8-ba59-20165b7b8043', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'29661c3a-3951-4a71-8c47-2dfd80258ed8', max_length=1024),
        ),
    ]
