SCHEDULED = 'SCHEDULED'
EDITABLE = 'EDITABLE'
FREEZE = 'FREEZE'
DELIVERED = 'DELIVERED'
NOT_DELIVERED = 'NOT_DELIVERED'
DEFAULT_DELIVERY_MSG = "Default Delivery Applied to:  "
TOTAL_WEEK_DAYS = 7
DELIVERY_PRIOR_DAYS = 2

CUSTOMIZATION_START_BEFORE_DELIVERY_DAYS = 2
CUSTOMIZATION_START_BEFORE_DELIVERY_DAYS_HOUR = 1
CUSTOMIZATION_END_DELIVERY_DAYS = 2
CUSTOMIZATION_END_DELIVERY_DAYS_HOUR = 22

HARVEST_EXPORT_HEADERS = ['Product Name', 'Total Quantity', 'Unit']
